name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-rust_stable-${{ hashFiles('**/Cargo.toml') }}
      - name: Format
        run: cargo fmt --all -- --check
  
  clippy-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Get date for registry cache
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.date.outputs.date }}
          restore-keys: ${{ runner.os }}-cargo-registry-
      - name: Get cargo-cache latest version
        id: cargocacheversion
        run: echo "::set-output name=version::$(cargo search 'cargo-cache' --limit 1 | head -n 1 | cut -d ' ' -f 3 | cut -d '"' -f 2)"
      - name: Cargo binaries cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/cargo-cache
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-cargo-binaries-${{ steps.cargocacheversion.outputs.version }}
      - name: Install cargo-cache
        run: cargo install cargo-cache --version ${{ steps.cargocacheversion.outputs.version }}
      - name: Clean cargo cache of old items
        run: cargo cache clean-unref
      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install -y libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev
      - name: Downgrade log
        run: cargo update -p log --precise 0.4.14
      - name: Clippy Smithay
        run: cargo clippy --features "test_all_features" -- -D warnings
      - name: Clippy Anvil
        run: cargo clippy --manifest-path "./anvil/Cargo.toml" --features "test_all_features" --no-deps -- -D warnings
      - name: Clippy Smallvil
        run: cargo clippy --manifest-path "./smallvil/Cargo.toml" --no-deps -- -D warnings
  
  check-msrv:
    env:
      RUSTFLAGS: "-D warnings"

    runs-on: ubuntu-22.04
    needs:
      - clippy-check
      - format

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@1.65.0
      - name: Get date for registry cache
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.date.outputs.date }}
          restore-keys: ${{ runner.os }}-cargo-registry-
      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install -y libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev
      - name: Downgrade log
        run: cargo update -p log --precise 0.4.14
      - name: Check
        run: cargo check --features "test_all_features"

  check-minimal:
    env:
      RUSTFLAGS: "-D warnings"

    runs-on: ubuntu-22.04
    needs:
      - clippy-check
      - format

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Rust toolchain
        # currently nightly has an ICE affecting bytemuck
        # see: https://github.com/Lokathor/bytemuck/issues/197
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-06-17
      - name: Get date for registry cache
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.date.outputs.date }}
          restore-keys: ${{ runner.os }}-cargo-registry-
      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install -y libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev
      - name: Downgrade to minimal dependencies
        run: cargo update -Z minimal-versions
      - name: Check
        run: cargo check --features "test_all_features"

  smithay-tests:
    needs:
      - format
      - clippy-check
    strategy:
      fail-fast: false
      matrix:
        features:
        - ''
        - backend_winit
        - backend_drm
        - backend_gbm
        - backend_egl
        - backend_libinput
        - backend_udev
        - backend_session
        - backend_session_libseat
        - backend_vulkan
        - backend_x11
        - desktop
        - renderer_gl
        - renderer_glow
        - renderer_multi
        - wayland_frontend
        - xwayland
        - default
        - test_all_features

    env:
      RUSTFLAGS: "-D warnings"

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get date for registry cache
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.date.outputs.date }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install -y libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev

      - name: Downgrade log
        run: cargo update -p log --precise 0.4.14
      
      - name: Test features
        env:
          RUST_BACKTRACE: full
        run: cargo test --no-default-features --features "${{ matrix.features }}"

  smallvil:
    needs:
      - format
      - clippy-check
      - smithay-tests
    strategy:
      fail-fast: false

    env:
      RUSTFLAGS: "-D warnings"

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get date for registry cache
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.date.outputs.date }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install -y libxkbcommon-dev libegl1-mesa-dev libwayland-dev
      
      - name: Downgrade log
        run: cargo update -p log --precise 0.4.14
      
      - name: Test smallvil
        env:
          RUST_BACKTRACE: full
        run: cargo test --manifest-path "./smallvil/Cargo.toml"

  anvil-tests:
    needs:
      - format
      - clippy-check
      - smithay-tests
    strategy:
      fail-fast: false
      matrix:
        features:
        - ''
        - egl
        - winit
        - udev
        - x11
        - default
        - test_all_features

    env:
      RUSTFLAGS: "-D warnings"

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get date for registry cache
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.date.outputs.date }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install -y libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev
      
      - name: Downgrade log
        run: cargo update -p log --precise 0.4.14
      
      - name: Test features
        env:
          RUST_BACKTRACE: full
        run: cargo test --manifest-path "./anvil/Cargo.toml" --no-default-features --features "${{ matrix.features }}"

  anvil-wlcs:
    needs:
      - format
      - clippy-check
      - smithay-tests
      - anvil-tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: "Core tests"
            gtest_filter: "SelfTest*:FrameSubmission*"
            flag: core
          - job_name: "Output tests"
            gtest_filter: "XdgOutputV1Test*"
            flag: output
          - job_name: "Pointer input tests"
            gtest_filter: "*/SurfacePointerMotionTest*:RelativePointer*"
            flag: pointer-input
          - job_name: "Bad Buffer Test"
            gtest_filter: "BadBufferTest*"
            flag: buffer 

    name: "WLCS: ${{ matrix.job_name }}"

    env:
      RUSTFLAGS: "-D warnings"
      GRCOV_VERSION: "0.8.10"

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get date for registry cache
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.date.outputs.date }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview

      - name: grcov cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/grcov
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-grcov-${{ env.GRCOV_VERSION }}

      - name: Install grcov
        run: cargo install grcov --version ${{ env.GRCOV_VERSION }}

      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install -y cmake libgtest-dev google-mock libboost-dev libxkbcommon-dev libwayland-dev

      - name: WLCS build cache
        uses: actions/cache@v3
        with:
          path: wlcs
          key: ${{ runner.os }}-build-wlcs-${{ hashFiles('./compile_wlcs.sh') }}

      - name: Build WLCS
        run: ./compile_wlcs.sh

      - name: Downgrade log
        run: cargo update -p log --precise 0.4.14

      - name: Build anvil WLCS plugin
        env:
          RUST_BACKTRACE: full
          RUSTFLAGS: "-Cinstrument-coverage --cfg coverage"
        run: cargo build --manifest-path "./wlcs_anvil/Cargo.toml"

      - name: Run test suite
        run: ./wlcs/wlcs ./target/debug/libwlcs_anvil.so --gtest_filter="${{ matrix.gtest_filter }}"
        env:
          LLVM_PROFILE_FILE: "anvil-wlcs-%p-%m.profraw"

      - name: Coverage
        run: grcov . --binary-path ./target/debug -s . -t lcov --branch --llvm --ignore-not-existing --ignore '*/examples/*' --ignore '*/tests/*' --ignore '*/.cargo/registry/*' --excl-br-start "mod tests \{" --excl-start "mod tests \{" --excl-br-line "#\[derive\(" --excl-line "#\[derive\(" -o lcov.info

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          flags: wlcs-${{ matrix.flag }}

  doc:
    name: Documentation on Github Pages
    runs-on: ubuntu-22.04
    needs:
      - smithay-tests

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get date for registry cache
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cargo registry cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ steps.date.outputs.date }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Rust toolchain
        # currently nightly has an ICE affecting bytemuck
        # see: https://github.com/Lokathor/bytemuck/issues/197
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-06-17

      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install -y libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev
      
      - name: Downgrade log
        run: cargo update -p log --precise 0.4.14
      
      - name: Build Documentation
        env: 
          RUSTDOCFLAGS: --cfg=docsrs
        run: cargo doc --no-deps --features "test_all_features" -p smithay -p calloop:0.10.6 -p drm -p gbm -p input -p nix:0.26.2 -p udev -p slog -p wayland-server -p wayland-backend -p wayland-protocols:0.30.0 -p winit -p x11rb
        
      - name: Setup index
        run: cp ./doc_index.html ./target/doc/index.html

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true
